version: '3'

services:
  redis-service:
    image: redis:alpine
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

  app-db:
    image: postgres:alpine
    container_name: app-db
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5437:5432
    volumes:
      - './volumes/db/pg:/var/lib/postgresql/data'

  app:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DB_URL=app-db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=jwt-secret
      - REDIS_PASSWORD=redis-password
      - REDIS_HOST=redis-service
    depends_on:
      redis-service:
        condition: service_healthy
      app-db:
        condition: service_healthy
    ports:
      - '6000:5000'
      - '6001:5001'
    volumes:
      - ./:/usr/app
